// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCoSzJ5qRmjgGY-5tHKq2AyUh6JFkMzdQ',
    appId: '1:59592844887:web:a2c251a919cd721ab1a512',
    messagingSenderId: '59592844887',
    projectId: 'smart-drip-iot',
    authDomain: 'smart-drip-iot.firebaseapp.com',
    databaseURL: 'https://smart-drip-iot-default-rtdb.firebaseio.com',
    storageBucket: 'smart-drip-iot.firebasestorage.app',
    measurementId: 'G-YNQJZXBYZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVC5gJm0YV-fGiN4n3ndEjih6v3ymDWrU',
    appId: '1:59592844887:android:40c0c9a6fd2a0decb1a512',
    messagingSenderId: '59592844887',
    projectId: 'smart-drip-iot',
    databaseURL: 'https://smart-drip-iot-default-rtdb.firebaseio.com',
    storageBucket: 'smart-drip-iot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqa7C_zt5ECKjLHx4HVWO2NfgbWjMFK3s',
    appId: '1:59592844887:ios:6d927b00d1888324b1a512',
    messagingSenderId: '59592844887',
    projectId: 'smart-drip-iot',
    databaseURL: 'https://smart-drip-iot-default-rtdb.firebaseio.com',
    storageBucket: 'smart-drip-iot.firebasestorage.app',
    iosBundleId: 'com.example.testMonitoringApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqa7C_zt5ECKjLHx4HVWO2NfgbWjMFK3s',
    appId: '1:59592844887:ios:6d927b00d1888324b1a512',
    messagingSenderId: '59592844887',
    projectId: 'smart-drip-iot',
    databaseURL: 'https://smart-drip-iot-default-rtdb.firebaseio.com',
    storageBucket: 'smart-drip-iot.firebasestorage.app',
    iosBundleId: 'com.example.testMonitoringApps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCoSzJ5qRmjgGY-5tHKq2AyUh6JFkMzdQ',
    appId: '1:59592844887:web:46a818001afee182b1a512',
    messagingSenderId: '59592844887',
    projectId: 'smart-drip-iot',
    authDomain: 'smart-drip-iot.firebaseapp.com',
    databaseURL: 'https://smart-drip-iot-default-rtdb.firebaseio.com',
    storageBucket: 'smart-drip-iot.firebasestorage.app',
    measurementId: 'G-Q8EB1PFVYK',
  );
}
